sonar.projectKey=Ksuniqum23_frontend-project-11
sonar.organization=ksuniqum23

# Источники для анализа
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**,__tests__/**

# Тесты
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**

# Покрытие
sonar.javascript.lcov.reportPaths=coverage/lcov.info