name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run Qlty analysis
        run: |
          qlty analyze > qlty_results.txt
      - name: Update README.md
        run: |
          echo "## Qlty Results" >> README.md
          cat qlty_results.txt >> README.md